apiVersion: v1
kind: Service
# VIOLATION: Policy ID: ckv-k8s-21
# VIOLATION: Title: The default namespace should not be used
# VIOLATION: Severity: Low
# VIOLATION: Compliance: CIS
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
{{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "hello-world.selectorLabels" . | nindent 4 }}
