{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
# VIOLATION: Policy ID: ckv-k8s-21
# VIOLATION: Title: The default namespace should not be used
# VIOLATION: Severity: Low
# VIOLATION: Compliance: CIS
metadata:
  name: {{ include "hello-world.serviceAccountName" . }}
  labels:
{{- include "hello-world.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
